server:
  port: 11118
spring:
  cloud:
    gateway:
      routes:
        - id: test_filter
          uri: https://www.naver.com
          predicates:
            - Path=/test/**
          filters:
            - AuthCheckFilter


