
server:
  port: 22228



spring:
  r2dbc:
#    url: r2dbc:pool:mariadb://localhost:3306/keycloak_sample_db
    url: r2dbc:pool:mariadb://maestro.okestro.cloud:3306/keycloak
    username: keycloak
    password: keycloak